import './globals.css';
import './style/material-design-iconic-font/css/material-design-iconic-font.min.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en" className='theme-dark'>
      <body>
        {children}
      </body>
    </html>
  )
}
